// <auto-generated />
namespace qlcdvien.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class delete_Motangan_hoatdongCd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(delete_Motangan_hoatdongCd));
        
        string IMigrationMetadata.Id
        {
            get { return "201812270958599_delete_Motangan_hoatdongCd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
